/**
 * Canonical brand roster — used to seed the supplier brand picker, the "Brand"
 * filters and the brand autocomplete. Suppliers can add brands beyond this list
 * at any time (e.g. a brand the store starts carrying later).
 */
export const BRAND_ROSTER = Array.from(
  new Set(
    [
      // Row 1
      "4GAMES",
      "AOC",
      "AORUS",
      "Apacer",
      "Apple",
      "ASUS",
      "BenQ",
      "Bosch",
      "Brother",
      "Canon",
      "Cisco",
      "Colorful",
      "Cooler Master",
      "Corsair",
      "Cougar",
      "Crucial",
      "Dahua",
      "DeepCool",
      "Epson",
      "Fortinet",
      "Fractal Design",
      "FSP",
      "GALAX",
      "Gigabyte",
      "GST",
      "Hikvision",
      "Honeywell",
      "HP",
      "iGame",
      "Imou",
      "In Win",
      "Infinix",
      "Intel",
      "Kingston",
      "Lexar",
      "Lian Li",
      "Montech",
      "MSI",
      "NVIDIA",
      "NZXT",
      "OPPO",
      "Palit",
      "Phanteks",
      "Razer",
      "Realme",
      "RØDE",
      "Samsung",
      "Sapphire",
      "Schlage",
      "Seagate",
      "SilverStone",
      "SteelSeries",
      "T-Force",
      "Tapo",
      "TeamGroup",
      "Tenda",
      "Thermaltake",
      "TNO",
      "TP-Link",
      "TUF Gaming",
      "WD",
      "Western Digital",
      "XFX",
      "XPG",
      "ZKTeco",
      // Row 2
      "GALAX",
      "DeepCool",
      "TeamGroup",
      "Thermaltake",
      "iGame",
      "Razer",
      "Corsair",
      "NVIDIA",
      "Apacer",
      "Kingston",
      "WD / Western Digital",
      "Sapphire",
      "Phanteks",
      "AORUS",
      "In Win",
      "Cooler Master",
      "Montech",
      "Lexar",
      "Hikvision",
      "Honeywell",
      "Bosch",
      "Fortinet",
      "ZKTeco",
      // Row 3
      "T-Force",
      "Cougar",
      "SADES",
      "SteelSeries",
      "Seagate",
      "Crucial",
      "XPG",
      "Colorful",
      "Gigabyte",
      "RØDE",
      "MSI",
      "XFX",
      "TUF Gaming",
      "TP-Link",
      "Tapo",
      "Imou",
      "GST",
      "Cisco",
      "OPPO",
      "Apple",
      "Epson",
      "Canon",
      "Realme",
      "Infinix",
      "HP",
    ]
      .map((brand) => brand.trim())
      .filter(Boolean),
  ),
).sort((a, b) => a.localeCompare(b));