/**
 * DEMO DATA — fictional but realistic PC retail dataset.
 * Replace this module with real API responses when the backend lands.
 */
import type {
  AppNotification,
  AuditLog,
  Build,
  Customer,
  InventoryItem,
  InventoryMovement,
  Order,
  Product,
  Quote,
  SerialNumber,
  ServiceTicket,
  User,
  Warranty,
} from "./types";

const now = Date.now();
const daysAgo = (d: number, h = 10) => {
  const x = new Date(now - d * 86400000);
  x.setHours(h, (d * 7) % 60, 0, 0);
  return x.toISOString();
};
const daysAhead = (d: number) => new Date(now + d * 86400000).toISOString();

export const demoUsers: User[] = [
  {
    id: "u-1",
    name: "Justine Ramos",
    email: "demo@dpcnexus.local",
    role: "owner",
    initials: "JR",
  },
  { id: "u-2", name: "Mika Santos", email: "admin@dpcnexus.local", role: "admin", initials: "MS" },
  {
    id: "u-3",
    name: "Paolo Cruz",
    email: "cashier@dpcnexus.local",
    role: "cashier",
    initials: "PC",
  },
  {
    id: "u-4",
    name: "Ken Villareal",
    email: "tech@dpcnexus.local",
    role: "technician",
    initials: "KV",
  },
  {
    id: "u-5",
    name: "Dana Lim",
    email: "stock@dpcnexus.local",
    role: "inventory",
    initials: "DL",
  },
];

export const products: Product[] = [
  {
    id: "p-cpu-7800x3d",
    sku: "CPU-AMD-7800X3D",
    name: "AMD Ryzen 7 7800X3D",
    brand: "AMD",
    category: "CPU",
    price: 21500,
    cost: 18200,
    serialTracked: true,
    warrantyMonths: 36,
    location: "A1-01",
    supplier: "Nexlogic Distribution",
    specs: { socket: "AM5", tdp: 120, cores: 8 },
  },
  {
    id: "p-cpu-7600",
    sku: "CPU-AMD-7600",
    name: "AMD Ryzen 5 7600",
    brand: "AMD",
    category: "CPU",
    price: 11250,
    cost: 9600,
    serialTracked: true,
    warrantyMonths: 36,
    location: "A1-02",
    supplier: "Nexlogic Distribution",
    specs: { socket: "AM5", tdp: 65, cores: 6 },
  },
  {
    id: "p-cpu-14600kf",
    sku: "CPU-INT-14600KF",
    name: "Intel Core i5-14600KF",
    brand: "Intel",
    category: "CPU",
    price: 15400,
    cost: 13100,
    serialTracked: true,
    warrantyMonths: 36,
    location: "A1-03",
    supplier: "Silicon Bay Trading",
    specs: { socket: "LGA1700", tdp: 125, cores: 14 },
  },
  {
    id: "p-gpu-5070",
    sku: "GPU-RTX5070",
    name: "RTX 5070 Gaming OC 12GB",
    brand: "Gigabyte",
    category: "GPU",
    price: 42500,
    cost: 37800,
    serialTracked: true,
    warrantyMonths: 36,
    location: "B2-01",
    supplier: "Nexlogic Distribution",
    specs: { tdp: 250, length: "302mm" },
  },
  {
    id: "p-gpu-5060ti",
    sku: "GPU-RTX5060TI",
    name: "RTX 5060 Ti Ventus 16GB",
    brand: "MSI",
    category: "GPU",
    price: 28900,
    cost: 25400,
    serialTracked: true,
    warrantyMonths: 36,
    location: "B2-02",
    supplier: "Silicon Bay Trading",
    specs: { tdp: 180, length: "242mm" },
  },
  {
    id: "p-gpu-9070",
    sku: "GPU-RX9070",
    name: "Radeon RX 9070 Pulse 16GB",
    brand: "Sapphire",
    category: "GPU",
    price: 38900,
    cost: 34500,
    serialTracked: true,
    warrantyMonths: 36,
    location: "B2-03",
    supplier: "Pacific Components",
    specs: { tdp: 220, length: "290mm" },
  },
  {
    id: "p-mb-b650m",
    sku: "MB-MSI-B650M",
    name: "MSI B650M Gaming Plus WiFi",
    brand: "MSI",
    category: "Motherboard",
    price: 9450,
    cost: 7900,
    serialTracked: true,
    warrantyMonths: 36,
    location: "A2-01",
    supplier: "Silicon Bay Trading",
    specs: { socket: "AM5", memoryType: "DDR5", formFactor: "mATX" },
  },
  {
    id: "p-mb-x670e",
    sku: "MB-ASUS-X670E",
    name: "ASUS ROG Strix X670E-A",
    brand: "ASUS",
    category: "Motherboard",
    price: 24800,
    cost: 21200,
    serialTracked: true,
    warrantyMonths: 36,
    location: "A2-02",
    supplier: "Nexlogic Distribution",
    specs: { socket: "AM5", memoryType: "DDR5", formFactor: "ATX" },
  },
  {
    id: "p-mb-b760m",
    sku: "MB-GB-B760M",
    name: "Gigabyte B760M DS3H DDR5",
    brand: "Gigabyte",
    category: "Motherboard",
    price: 7850,
    cost: 6600,
    serialTracked: true,
    warrantyMonths: 36,
    location: "A2-03",
    supplier: "Pacific Components",
    specs: { socket: "LGA1700", memoryType: "DDR5", formFactor: "mATX" },
  },
  {
    id: "p-ram-fury32",
    sku: "RAM-KF-32GB-DDR5",
    name: "Kingston Fury Beast 32GB DDR5-6000",
    brand: "Kingston",
    category: "RAM",
    price: 4250,
    cost: 3450,
    serialTracked: false,
    warrantyMonths: 60,
    location: "A3-01",
    supplier: "Pacific Components",
    specs: { memoryType: "DDR5", capacity: "32GB" },
  },
  {
    id: "p-ram-vengeance16",
    sku: "RAM-CS-16GB-DDR5",
    name: "Corsair Vengeance 16GB DDR5-5600",
    brand: "Corsair",
    category: "RAM",
    price: 2650,
    cost: 2100,
    serialTracked: false,
    warrantyMonths: 60,
    location: "A3-02",
    supplier: "Pacific Components",
    specs: { memoryType: "DDR5", capacity: "16GB" },
  },
  {
    id: "p-ram-ddr4-16",
    sku: "RAM-KF-16GB-DDR4",
    name: "Kingston Fury Beast 16GB DDR4-3200",
    brand: "Kingston",
    category: "RAM",
    price: 1950,
    cost: 1500,
    serialTracked: false,
    warrantyMonths: 60,
    location: "A3-03",
    supplier: "Pacific Components",
    specs: { memoryType: "DDR4", capacity: "16GB" },
  },
  {
    id: "p-ssd-990pro",
    sku: "SSD-SAM-990P-1TB",
    name: "Samsung 990 PRO 1TB NVMe",
    brand: "Samsung",
    category: "Storage",
    price: 6450,
    cost: 5300,
    serialTracked: true,
    warrantyMonths: 60,
    location: "A4-01",
    supplier: "Nexlogic Distribution",
    specs: { capacity: "1TB", interface: "PCIe 4.0" },
  },
  {
    id: "p-ssd-p3plus",
    sku: "SSD-CRU-P3P-2TB",
    name: "Crucial P3 Plus 2TB NVMe",
    brand: "Crucial",
    category: "Storage",
    price: 7200,
    cost: 6100,
    serialTracked: true,
    warrantyMonths: 60,
    location: "A4-02",
    supplier: "Silicon Bay Trading",
    specs: { capacity: "2TB", interface: "PCIe 4.0" },
  },
  {
    id: "p-hdd-2tb",
    sku: "HDD-SEA-2TB",
    name: "Seagate Barracuda 2TB HDD",
    brand: "Seagate",
    category: "Storage",
    price: 3150,
    cost: 2600,
    serialTracked: true,
    warrantyMonths: 24,
    location: "A4-03",
    supplier: "Pacific Components",
    specs: { capacity: "2TB", interface: "SATA" },
  },
  {
    id: "p-psu-rm750e",
    sku: "PSU-CS-RM750E",
    name: "Corsair RM750e 750W 80+ Gold",
    brand: "Corsair",
    category: "PSU",
    price: 5950,
    cost: 4900,
    serialTracked: true,
    warrantyMonths: 84,
    location: "C1-01",
    supplier: "Pacific Components",
    specs: { wattage: 750, rating: "80+ Gold" },
  },
  {
    id: "p-psu-mag850",
    sku: "PSU-MSI-A850G",
    name: "MSI MAG A850GL 850W 80+ Gold",
    brand: "MSI",
    category: "PSU",
    price: 7150,
    cost: 6000,
    serialTracked: true,
    warrantyMonths: 120,
    location: "C1-02",
    supplier: "Silicon Bay Trading",
    specs: { wattage: 850, rating: "80+ Gold" },
  },
  {
    id: "p-psu-cv550",
    sku: "PSU-CS-CV550",
    name: "Corsair CV550 550W 80+ Bronze",
    brand: "Corsair",
    category: "PSU",
    price: 2950,
    cost: 2350,
    serialTracked: true,
    warrantyMonths: 36,
    location: "C1-03",
    supplier: "Pacific Components",
    specs: { wattage: 550, rating: "80+ Bronze" },
  },
  {
    id: "p-case-4000d",
    sku: "CASE-CS-4000D",
    name: "Corsair 4000D Airflow",
    brand: "Corsair",
    category: "Case",
    price: 5250,
    cost: 4300,
    serialTracked: false,
    warrantyMonths: 24,
    location: "D1-01",
    supplier: "Pacific Components",
    specs: { formFactor: "ATX", maxGpu: "360mm" },
  },
  {
    id: "p-case-nrp200",
    sku: "CASE-NR-P200",
    name: "Cooler Master NR200P mITX",
    brand: "Cooler Master",
    category: "Case",
    price: 5450,
    cost: 4500,
    serialTracked: false,
    warrantyMonths: 24,
    location: "D1-02",
    supplier: "Silicon Bay Trading",
    specs: { formFactor: "mITX", maxGpu: "330mm" },
  },
  {
    id: "p-cool-ak620",
    sku: "COOL-DD-AK620",
    name: "Deepcool AK620 Air Cooler",
    brand: "Deepcool",
    category: "Cooling",
    price: 3450,
    cost: 2750,
    serialTracked: false,
    warrantyMonths: 36,
    location: "C2-01",
    supplier: "Pacific Components",
    specs: { tdp: 260, type: "Air" },
  },
  {
    id: "p-cool-h100i",
    sku: "COOL-CS-H100I",
    name: "Corsair iCUE H100i 240mm AIO",
    brand: "Corsair",
    category: "Cooling",
    price: 8450,
    cost: 7100,
    serialTracked: true,
    warrantyMonths: 60,
    location: "C2-02",
    supplier: "Nexlogic Distribution",
    specs: { tdp: 250, type: "AIO" },
  },
  {
    id: "p-fan-arctic",
    sku: "FAN-ARC-P12-3PK",
    name: "Arctic P12 PWM 120mm (3-pack)",
    brand: "Arctic",
    category: "Fans",
    price: 1350,
    cost: 980,
    serialTracked: false,
    warrantyMonths: 24,
    location: "C2-03",
    supplier: "Pacific Components",
    specs: { size: "120mm" },
  },
  {
    id: "p-mon-odyssey",
    sku: "MON-SAM-G5-27",
    name: 'Samsung Odyssey G5 27" 165Hz',
    brand: "Samsung",
    category: "Monitor",
    price: 12900,
    cost: 10800,
    serialTracked: true,
    warrantyMonths: 36,
    location: "E1-01",
    supplier: "Nexlogic Distribution",
    specs: { size: '27"', refresh: "165Hz" },
  },
  {
    id: "p-kb-k70",
    sku: "KB-CS-K70-RGB",
    name: "Corsair K70 RGB Mechanical",
    brand: "Corsair",
    category: "Keyboard",
    price: 6250,
    cost: 5100,
    serialTracked: false,
    warrantyMonths: 24,
    location: "E2-01",
    supplier: "Pacific Components",
    specs: { switch: "MX Red" },
  },
  {
    id: "p-mouse-g502",
    sku: "MSE-LOG-G502X",
    name: "Logitech G502 X Wireless",
    brand: "Logitech",
    category: "Mouse",
    price: 7450,
    cost: 6200,
    serialTracked: false,
    warrantyMonths: 24,
    location: "E2-02",
    supplier: "Pacific Components",
    specs: { dpi: 25600 },
  },
  {
    id: "p-hs-cloud3",
    sku: "HS-HX-CLOUD3",
    name: "HyperX Cloud III Headset",
    brand: "HyperX",
    category: "Headset",
    price: 5450,
    cost: 4400,
    serialTracked: false,
    warrantyMonths: 24,
    location: "E2-03",
    supplier: "Silicon Bay Trading",
    specs: { connection: "Wired" },
  },
  {
    id: "p-net-ax3000",
    sku: "NET-TP-AX3000",
    name: "TP-Link Archer AX3000 Router",
    brand: "TP-Link",
    category: "Networking",
    price: 4250,
    cost: 3450,
    serialTracked: true,
    warrantyMonths: 24,
    location: "F1-01",
    supplier: "Pacific Components",
    specs: { standard: "WiFi 6" },
  },
  {
    id: "p-acc-paste",
    sku: "ACC-TG-KRYO",
    name: "Thermal Grizzly Kryonaut 2g",
    brand: "Thermal Grizzly",
    category: "Accessories",
    price: 950,
    cost: 690,
    serialTracked: false,
    warrantyMonths: 0,
    location: "F2-01",
    supplier: "Pacific Components",
    specs: {},
  },
  {
    id: "p-sw-win11",
    sku: "SW-MS-W11-PRO",
    name: "Windows 11 Pro OEM License",
    brand: "Microsoft",
    category: "Software",
    price: 8900,
    cost: 7400,
    serialTracked: false,
    warrantyMonths: 0,
    location: "—",
    supplier: "Microsoft PH",
    specs: {},
  },
  {
    id: "s-assembly",
    sku: "SRV-ASSEMBLY",
    name: "Custom Build Assembly",
    brand: "DPC",
    category: "Services",
    price: 2500,
    cost: 0,
    serialTracked: false,
    warrantyMonths: 3,
    location: "—",
    supplier: "In-house",
    specs: {},
    isService: true,
  },
  {
    id: "s-osinstall",
    sku: "SRV-OS-INSTALL",
    name: "OS Installation & Drivers",
    brand: "DPC",
    category: "Services",
    price: 1000,
    cost: 0,
    serialTracked: false,
    warrantyMonths: 1,
    location: "—",
    supplier: "In-house",
    specs: {},
    isService: true,
  },
  {
    id: "s-cable",
    sku: "SRV-CABLE-MGMT",
    name: "Premium Cable Management",
    brand: "DPC",
    category: "Services",
    price: 500,
    cost: 0,
    serialTracked: false,
    warrantyMonths: 0,
    location: "—",
    supplier: "In-house",
    specs: {},
    isService: true,
  },
  {
    id: "s-maintenance",
    sku: "SRV-MAINTENANCE",
    name: "PC Maintenance Service",
    brand: "DPC",
    category: "Services",
    price: 1500,
    cost: 0,
    serialTracked: false,
    warrantyMonths: 1,
    location: "—",
    supplier: "In-house",
    specs: {},
    isService: true,
  },
  {
    id: "s-diagnostic",
    sku: "SRV-DIAGNOSTIC",
    name: "Hardware Diagnostic",
    brand: "DPC",
    category: "Services",
    price: 800,
    cost: 0,
    serialTracked: false,
    warrantyMonths: 0,
    location: "—",
    supplier: "In-house",
    specs: {},
    isService: true,
  },
];

const stockTable: Record<string, [number, number, number, number, number]> = {
  // productId: [onHand, reserved, damaged, sold, reorderPoint]
  "p-cpu-7800x3d": [6, 2, 0, 34, 4],
  "p-cpu-7600": [11, 1, 0, 41, 5],
  "p-cpu-14600kf": [4, 0, 1, 22, 4],
  "p-gpu-5070": [5, 3, 0, 18, 4],
  "p-gpu-5060ti": [9, 1, 0, 27, 4],
  "p-gpu-9070": [3, 1, 0, 9, 3],
  "p-mb-b650m": [14, 2, 0, 55, 6],
  "p-mb-x670e": [3, 1, 0, 12, 3],
  "p-mb-b760m": [10, 0, 0, 31, 5],
  "p-ram-fury32": [22, 4, 0, 88, 10],
  "p-ram-vengeance16": [31, 2, 0, 120, 12],
  "p-ram-ddr4-16": [8, 0, 1, 64, 8],
  "p-ssd-990pro": [4, 1, 0, 47, 6],
  "p-ssd-p3plus": [12, 0, 0, 29, 5],
  "p-hdd-2tb": [7, 0, 0, 19, 4],
  "p-psu-rm750e": [13, 2, 0, 44, 6],
  "p-psu-mag850": [6, 1, 0, 17, 4],
  "p-psu-cv550": [2, 0, 0, 33, 5],
  "p-case-4000d": [9, 2, 0, 38, 4],
  "p-case-nrp200": [3, 0, 0, 11, 3],
  "p-cool-ak620": [15, 1, 0, 52, 6],
  "p-cool-h100i": [5, 1, 0, 21, 4],
  "p-fan-arctic": [26, 0, 0, 74, 10],
  "p-mon-odyssey": [7, 1, 0, 25, 3],
  "p-kb-k70": [10, 0, 0, 36, 5],
  "p-mouse-g502": [12, 1, 0, 42, 5],
  "p-hs-cloud3": [0, 0, 0, 28, 4],
  "p-net-ax3000": [8, 0, 0, 15, 3],
  "p-acc-paste": [34, 0, 0, 96, 10],
  "p-sw-win11": [18, 2, 0, 61, 6],
};

export const inventory: InventoryItem[] = products
  .filter((p) => !p.isService)
  .map((p) => {
    const [onHand, reserved, damaged, sold, reorderPoint] = stockTable[p.id] ?? [
      10, 0, 0, 0, 4,
    ];
    return { productId: p.id, onHand, reserved, damaged, sold, reorderPoint };
  });

function makeSerials(): SerialNumber[] {
  const out: SerialNumber[] = [];
  let n = 90210;
  for (const p of products.filter((x) => x.serialTracked)) {
    const inv = inventory.find((i) => i.productId === p.id)!;
    const total = inv.onHand;
    for (let i = 0; i < total; i++) {
      n += 137;
      const reserved = i < inv.reserved;
      out.push({
        id: `sn-${p.id}-${i}`,
        serial: `${p.sku.split("-").pop()}-${n}`,
        productId: p.id,
        status: reserved ? "reserved" : "in_stock",
      });
    }
  }
  // a few sold/installed units with traceability
  out.push(
    {
      id: "sn-sold-1",
      serial: "RTX5070-92831",
      productId: "p-gpu-5070",
      status: "installed",
      orderId: "DPC-10482",
      buildId: "BUILD-10482",
      customerId: "c-1",
      warrantyUntil: daysAhead(360),
    },
    {
      id: "sn-sold-2",
      serial: "7800X3D-81204",
      productId: "p-cpu-7800x3d",
      status: "installed",
      orderId: "DPC-10482",
      buildId: "BUILD-10482",
      customerId: "c-1",
      warrantyUntil: daysAhead(360),
    },
    {
      id: "sn-sold-3",
      serial: "990P-44120",
      productId: "p-ssd-990pro",
      status: "sold",
      orderId: "DPC-10479",
      customerId: "c-3",
      warrantyUntil: daysAhead(690),
    },
  );
  return out;
}

export const serials: SerialNumber[] = makeSerials();

export const customers: Customer[] = [
  {
    id: "c-1",
    name: "Juan Dela Cruz",
    email: "juan.delacruz@mailbox.ph",
    phone: "+63 917 224 8810",
    type: "individual",
    address: "Bacoor, Cavite",
    since: daysAgo(420),
    status: "active",
    notes: "Prefers AMD platforms. Repeat custom-build client.",
  },
  {
    id: "c-2",
    name: "Northline Creatives Inc.",
    email: "it@northlinecreatives.ph",
    phone: "+63 2 8842 1190",
    type: "business",
    address: "Ortigas Center, Pasig",
    since: daysAgo(300),
    status: "active",
    notes: "Workstation fleet, invoices net-15.",
  },
  {
    id: "c-3",
    name: "Maria Santiago",
    email: "m.santiago@mailbox.ph",
    phone: "+63 928 771 5502",
    type: "individual",
    address: "Quezon City",
    since: daysAgo(210),
    status: "active",
  },
  {
    id: "c-4",
    name: "Rafael Ong",
    email: "rafael.ong@mailbox.ph",
    phone: "+63 906 330 2214",
    type: "individual",
    address: "Makati City",
    since: daysAgo(160),
    status: "active",
  },
  {
    id: "c-5",
    name: "Bluewave Internet Cafe",
    email: "ops@bluewavecafe.ph",
    phone: "+63 933 108 7741",
    type: "business",
    address: "Imus, Cavite",
    since: daysAgo(540),
    status: "active",
    notes: "24 units on rolling upgrade cycle.",
  },
  {
    id: "c-6",
    name: "Ellaine Bautista",
    email: "ellaine.b@mailbox.ph",
    phone: "+63 915 442 0098",
    type: "individual",
    address: "Las Piñas City",
    since: daysAgo(75),
    status: "inactive",
  },
];

const item = (productId: string, qty = 1) => {
  const p = products.find((x) => x.id === productId)!;
  return { productId, name: p.name, sku: p.sku, qty, unitPrice: p.price };
};

function totals(
  items: { qty: number; unitPrice: number }[],
  discount = 0,
  serviceTotal = 0,
) {
  const gross = items.reduce((s, i) => s + i.qty * i.unitPrice, 0) + serviceTotal;
  const net = gross - discount;
  const subtotal = Math.round((net / 1.12) * 100) / 100;
  const tax = Math.round((net - subtotal) * 100) / 100;
  return { subtotal, tax, total: net };
}

function order(
  id: string,
  customerId: string | null,
  customerName: string,
  type: Order["type"],
  status: Order["status"],
  items: ReturnType<typeof item>[],
  createdAt: string,
  opts: Partial<Order> = {},
): Order {
  const discount = opts.discount ?? 0;
  const serviceTotal = opts.serviceTotal ?? 0;
  const t = totals(items, discount, serviceTotal);
  return {
    id,
    customerId,
    customerName,
    type,
    status,
    items,
    discount,
    serviceTotal,
    subtotal: t.subtotal,
    tax: t.tax,
    total: t.total,
    payment: opts.payment ?? {
      id: `pay-${id}`,
      method: "cash",
      amount: t.total,
      at: createdAt,
    },
    createdAt,
    cashier: opts.cashier ?? "Paolo Cruz",
    timeline: opts.timeline ?? [
      { label: "Order created", at: createdAt, actor: "Paolo Cruz", state: "done" },
      { label: "Payment received", at: createdAt, actor: "Paolo Cruz", state: "done" },
      { label: "Released to customer", at: createdAt, actor: "Paolo Cruz", state: "done" },
    ],
    ...opts,
  };
}

export const orders: Order[] = [
  order(
    "DPC-10482",
    "c-1",
    "Juan Dela Cruz",
    "custom_build",
    "assembly",
    [
      item("p-cpu-7800x3d"),
      item("p-gpu-5070"),
      item("p-mb-b650m"),
      item("p-ram-fury32"),
      item("p-ssd-990pro"),
      item("p-psu-rm750e"),
      item("p-case-4000d"),
      item("p-cool-ak620"),
    ],
    daysAgo(0, 9),
    {
      serviceTotal: 4000,
      discount: 2000,
      buildId: "BUILD-10482",
      quoteId: "QT-10231",
      payment: { id: "pay-1", method: "bank", amount: 98500, at: daysAgo(0, 9) },
      timeline: [
        { label: "Payment received", at: daysAgo(0, 9), actor: "Paolo Cruz", state: "done" },
        { label: "Parts reserved", at: daysAgo(0, 10), actor: "Dana Lim", state: "done" },
        {
          label: "Assembly started",
          at: daysAgo(0, 11),
          actor: "Ken Villareal",
          state: "active",
        },
        { label: "QA testing", at: "", state: "pending" },
        { label: "Build completed", at: "", state: "pending" },
        { label: "Ready for release", at: "", state: "pending" },
        { label: "Released", at: "", state: "pending" },
      ],
    },
  ),
  order(
    "DPC-10481",
    "c-3",
    "Maria Santiago",
    "retail",
    "completed",
    [item("p-gpu-5070")],
    daysAgo(0, 13),
    { payment: { id: "pay-2", method: "gcash", amount: 42500, at: daysAgo(0, 13) } },
  ),
  order(
    "DPC-10480",
    null,
    "Walk-in Customer",
    "retail",
    "completed",
    [item("p-ram-fury32")],
    daysAgo(0, 14),
  ),
  order(
    "DPC-10479",
    "c-4",
    "Rafael Ong",
    "service",
    "completed",
    [item("s-maintenance")],
    daysAgo(1, 15),
    { payment: { id: "pay-4", method: "cash", amount: 1500, at: daysAgo(1, 15) } },
  ),
  order(
    "DPC-10478",
    "c-2",
    "Northline Creatives Inc.",
    "retail",
    "ready",
    [item("p-mon-odyssey", 3), item("p-kb-k70", 3), item("p-mouse-g502", 3)],
    daysAgo(1, 11),
    {
      discount: 3500,
      payment: { id: "pay-5", method: "bank", amount: 74300, at: daysAgo(1, 11) },
      cashier: "Mika Santos",
      timeline: [
        { label: "Payment received", at: daysAgo(1, 11), actor: "Mika Santos", state: "done" },
        { label: "Items picked", at: daysAgo(1, 12), actor: "Dana Lim", state: "done" },
        { label: "Ready for pickup", at: daysAgo(1, 13), actor: "Dana Lim", state: "active" },
        { label: "Released", at: "", state: "pending" },
      ],
    },
  ),
  order(
    "DPC-10477",
    "c-5",
    "Bluewave Internet Cafe",
    "retail",
    "processing",
    [item("p-cpu-7600", 4), item("p-mb-b650m", 4), item("p-ram-vengeance16", 8)],
    daysAgo(2, 10),
    {
      payment: { id: "pay-6", method: "bank", amount: 106000, at: daysAgo(2, 10) },
    },
  ),
  order(
    "DPC-10476",
    "c-6",
    "Ellaine Bautista",
    "retail",
    "refunded",
    [item("p-hs-cloud3")],
    daysAgo(4, 16),
    { payment: { id: "pay-7", method: "card", amount: 5450, at: daysAgo(4, 16) } },
  ),
  order(
    "DPC-10475",
    "c-1",
    "Juan Dela Cruz",
    "retail",
    "completed",
    [item("p-ssd-p3plus"), item("p-fan-arctic", 2)],
    daysAgo(6, 14),
  ),
  order(
    "DPC-10474",
    "c-3",
    "Maria Santiago",
    "retail",
    "pending",
    [item("p-gpu-9070")],
    daysAgo(7, 12),
    { payment: null, status: "pending" },
  ),
];

export const quotes: Quote[] = [
  {
    id: "QT-10245",
    customerId: "c-4",
    customerName: "Rafael Ong",
    status: "pending",
    items: [
      item("p-cpu-14600kf"),
      item("p-mb-b760m"),
      item("p-ram-vengeance16", 2),
      item("p-gpu-5060ti"),
      item("p-ssd-990pro"),
      item("p-psu-rm750e"),
      item("p-case-4000d"),
    ],
    discount: 1500,
    serviceTotal: 4000,
    subtotal: 0,
    tax: 0,
    total: 0,
    createdAt: daysAgo(1, 14),
    expiresAt: daysAhead(6),
    notes: "Editing workstation, prefers quiet operation.",
    preparedBy: "Mika Santos",
  },
  {
    id: "QT-10244",
    customerId: "c-5",
    customerName: "Bluewave Internet Cafe",
    status: "sent",
    items: [item("p-cpu-7600", 6), item("p-mb-b650m", 6), item("p-ram-vengeance16", 12)],
    discount: 6000,
    serviceTotal: 9000,
    subtotal: 0,
    tax: 0,
    total: 0,
    createdAt: daysAgo(3, 11),
    expiresAt: daysAhead(11),
    notes: "Phase 2 of cafe upgrade.",
    preparedBy: "Justine Ramos",
  },
  {
    id: "QT-10243",
    customerId: "c-2",
    customerName: "Northline Creatives Inc.",
    status: "approved",
    items: [item("p-mon-odyssey", 4)],
    discount: 2000,
    serviceTotal: 0,
    subtotal: 0,
    tax: 0,
    total: 0,
    createdAt: daysAgo(5, 10),
    expiresAt: daysAhead(9),
    preparedBy: "Mika Santos",
  },
  {
    id: "QT-10242",
    customerId: "c-3",
    customerName: "Maria Santiago",
    status: "draft",
    items: [item("p-gpu-9070"), item("p-psu-mag850")],
    discount: 0,
    serviceTotal: 500,
    subtotal: 0,
    tax: 0,
    total: 0,
    createdAt: daysAgo(2, 16),
    expiresAt: daysAhead(12),
    preparedBy: "Paolo Cruz",
  },
  {
    id: "QT-10231",
    customerId: "c-1",
    customerName: "Juan Dela Cruz",
    status: "converted",
    items: [item("p-cpu-7800x3d"), item("p-gpu-5070"), item("p-mb-b650m")],
    discount: 2000,
    serviceTotal: 4000,
    subtotal: 0,
    tax: 0,
    total: 0,
    createdAt: daysAgo(9, 15),
    expiresAt: daysAgo(-5),
    orderId: "DPC-10482",
    buildId: "BUILD-10482",
    preparedBy: "Justine Ramos",
  },
  {
    id: "QT-10228",
    customerId: "c-6",
    customerName: "Ellaine Bautista",
    status: "expired",
    items: [item("p-kb-k70"), item("p-mouse-g502")],
    discount: 0,
    serviceTotal: 0,
    subtotal: 0,
    tax: 0,
    total: 0,
    createdAt: daysAgo(40, 12),
    expiresAt: daysAgo(26),
    preparedBy: "Paolo Cruz",
  },
];

// normalize quote totals
for (const q of quotes) {
  const t = totals(q.items, q.discount, q.serviceTotal);
  q.subtotal = t.subtotal;
  q.tax = t.tax;
  q.total = t.total;
}

const standardQa = (passedCount: number) => {
  const hw = [
    "CPU installed & seated",
    "RAM detected (all slots)",
    "GPU detected",
    "Storage detected",
    "BIOS configured / EXPO enabled",
    "Cable management complete",
  ];
  const test = [
    "POST successful",
    "Memory test (1 pass)",
    "CPU stress test 30 min",
    "GPU stress test 30 min",
    "Storage health check",
    "Thermal / temperature test",
  ];
  const all = [
    ...hw.map((l) => ({ label: l, group: "hardware" as const })),
    ...test.map((l) => ({ label: l, group: "testing" as const })),
  ];
  return all.map((c, i) => ({ ...c, passed: i < passedCount ? true : null }));
};

export const builds: Build[] = [
  {
    id: "BUILD-10482",
    customerId: "c-1",
    customerName: "Juan Dela Cruz",
    purpose: "1440p gaming / streaming",
    budget: 100000,
    status: "assembly",
    components: [
      { slot: "CPU", productId: "p-cpu-7800x3d", qty: 1 },
      { slot: "Motherboard", productId: "p-mb-b650m", qty: 1 },
      { slot: "RAM", productId: "p-ram-fury32", qty: 1 },
      { slot: "GPU", productId: "p-gpu-5070", qty: 1 },
      { slot: "Storage", productId: "p-ssd-990pro", qty: 1 },
      { slot: "PSU", productId: "p-psu-rm750e", qty: 1 },
      { slot: "Case", productId: "p-case-4000d", qty: 1 },
      { slot: "Cooling", productId: "p-cool-ak620", qty: 1 },
    ],
    services: [
      { label: "Assembly", amount: 2500 },
      { label: "Windows installation", amount: 1000 },
      { label: "Cable management", amount: 500 },
    ],
    technician: "Ken Villareal",
    createdAt: daysAgo(3, 10),
    orderId: "DPC-10482",
    quoteId: "QT-10231",
    notes: "Customer requested quiet fan curve and white cable extensions.",
    qa: standardQa(6),
    qaResult: null,
  },
  {
    id: "BUILD-10479",
    customerId: "c-4",
    customerName: "Rafael Ong",
    purpose: "Video editing workstation",
    budget: 120000,
    status: "quoted",
    components: [
      { slot: "CPU", productId: "p-cpu-14600kf", qty: 1 },
      { slot: "Motherboard", productId: "p-mb-b760m", qty: 1 },
      { slot: "RAM", productId: "p-ram-vengeance16", qty: 2 },
      { slot: "GPU", productId: "p-gpu-5060ti", qty: 1 },
      { slot: "Storage", productId: "p-ssd-990pro", qty: 1 },
      { slot: "PSU", productId: "p-psu-rm750e", qty: 1 },
      { slot: "Case", productId: "p-case-4000d", qty: 1 },
    ],
    services: [
      { label: "Assembly", amount: 2500 },
      { label: "Windows installation", amount: 1000 },
      { label: "Cable management", amount: 500 },
    ],
    technician: "Ken Villareal",
    createdAt: daysAgo(1, 14),
    quoteId: "QT-10245",
    qa: standardQa(0),
    qaResult: null,
  },
  {
    id: "BUILD-10477",
    customerId: "c-3",
    customerName: "Maria Santiago",
    purpose: "Compact ITX gaming build",
    budget: 90000,
    status: "testing",
    components: [
      { slot: "CPU", productId: "p-cpu-7600", qty: 1 },
      { slot: "Motherboard", productId: "p-mb-b650m", qty: 1 },
      { slot: "RAM", productId: "p-ram-fury32", qty: 1 },
      { slot: "GPU", productId: "p-gpu-9070", qty: 1 },
      { slot: "Storage", productId: "p-ssd-p3plus", qty: 1 },
      { slot: "PSU", productId: "p-psu-cv550", qty: 1 },
      { slot: "Case", productId: "p-case-nrp200", qty: 1 },
      { slot: "Cooling", productId: "p-cool-h100i", qty: 1 },
    ],
    services: [
      { label: "Assembly", amount: 2500 },
      { label: "Cable management", amount: 500 },
    ],
    technician: "Ken Villareal",
    createdAt: daysAgo(4, 9),
    qa: standardQa(9),
    qaResult: null,
    notes: "PSU headroom is tight with RX 9070 — flag for review.",
  },
  {
    id: "BUILD-10474",
    customerId: "c-2",
    customerName: "Northline Creatives Inc.",
    purpose: "Studio render node",
    budget: 150000,
    status: "consultation",
    components: [{ slot: "CPU", productId: "p-cpu-7800x3d", qty: 1 }],
    services: [{ label: "Assembly", amount: 2500 }],
    technician: "Unassigned",
    createdAt: daysAgo(2, 16),
    qa: standardQa(0),
    qaResult: null,
  },
  {
    id: "BUILD-10468",
    customerId: "c-5",
    customerName: "Bluewave Internet Cafe",
    purpose: "Cafe station unit #7",
    budget: 45000,
    status: "ready",
    components: [
      { slot: "CPU", productId: "p-cpu-7600", qty: 1 },
      { slot: "Motherboard", productId: "p-mb-b650m", qty: 1 },
      { slot: "RAM", productId: "p-ram-vengeance16", qty: 1 },
      { slot: "Storage", productId: "p-ssd-p3plus", qty: 1 },
      { slot: "PSU", productId: "p-psu-cv550", qty: 1 },
      { slot: "Case", productId: "p-case-4000d", qty: 1 },
    ],
    services: [{ label: "Assembly", amount: 2500 }],
    technician: "Ken Villareal",
    createdAt: daysAgo(8, 11),
    qa: standardQa(12),
    qaResult: "pass",
  },
  {
    id: "BUILD-10461",
    customerId: "c-1",
    customerName: "Juan Dela Cruz",
    purpose: "Secondary office PC",
    budget: 40000,
    status: "released",
    components: [
      { slot: "CPU", productId: "p-cpu-7600", qty: 1 },
      { slot: "Motherboard", productId: "p-mb-b760m", qty: 1 },
      { slot: "RAM", productId: "p-ram-ddr4-16", qty: 1 },
    ],
    services: [{ label: "Assembly", amount: 2500 }],
    technician: "Ken Villareal",
    createdAt: daysAgo(30, 10),
    qa: standardQa(12),
    qaResult: "pass",
  },
];

export const services: ServiceTicket[] = [
  {
    id: "SRV-10482",
    customerId: "c-1",
    customerName: "Juan Dela Cruz",
    device: "Custom PC — Ryzen 7 5800X",
    issue: "Random shutdown under gaming load after ~20 minutes.",
    diagnosis: "Suspect PSU degradation; ruling out thermal throttling first.",
    status: "diagnosing",
    technician: "Ken Villareal",
    parts: [],
    labor: 800,
    estimatedCost: 800,
    actualCost: null,
    createdAt: daysAgo(0, 10),
    timeline: [
      { label: "Unit received", at: daysAgo(0, 10), actor: "Paolo Cruz", state: "done" },
      { label: "Diagnostics started", at: daysAgo(0, 12), actor: "Ken Villareal", state: "active" },
      { label: "Repair", at: "", state: "pending" },
      { label: "Ready for release", at: "", state: "pending" },
    ],
  },
  {
    id: "SRV-10481",
    customerId: "c-5",
    customerName: "Bluewave Internet Cafe",
    device: "Cafe unit #12",
    issue: "No display output after power outage.",
    diagnosis: "Motherboard VRM failure confirmed. Replacement required.",
    status: "waiting_parts",
    technician: "Ken Villareal",
    parts: [{ productId: "p-mb-b650m", name: "MSI B650M Gaming Plus WiFi", qty: 1, price: 9450 }],
    labor: 1200,
    estimatedCost: 10650,
    actualCost: null,
    createdAt: daysAgo(2, 9),
    timeline: [
      { label: "Unit received", at: daysAgo(2, 9), actor: "Dana Lim", state: "done" },
      { label: "Diagnosis complete", at: daysAgo(2, 14), actor: "Ken Villareal", state: "done" },
      { label: "Waiting for parts", at: daysAgo(1, 9), actor: "Dana Lim", state: "active" },
      { label: "Repair", at: "", state: "pending" },
    ],
  },
  {
    id: "SRV-10480",
    customerId: "c-3",
    customerName: "Maria Santiago",
    device: "Laptop — Acer Nitro 5",
    issue: "Overheating and loud fan noise.",
    diagnosis: "Dust buildup, dried thermal paste.",
    status: "ready",
    technician: "Ken Villareal",
    parts: [{ productId: "p-acc-paste", name: "Thermal Grizzly Kryonaut 2g", qty: 1, price: 950 }],
    labor: 1500,
    estimatedCost: 2450,
    actualCost: 2450,
    createdAt: daysAgo(3, 11),
    timeline: [
      { label: "Unit received", at: daysAgo(3, 11), actor: "Paolo Cruz", state: "done" },
      { label: "Diagnosis complete", at: daysAgo(3, 15), actor: "Ken Villareal", state: "done" },
      { label: "Repair complete", at: daysAgo(2, 11), actor: "Ken Villareal", state: "done" },
      { label: "Ready for release", at: daysAgo(2, 12), actor: "Ken Villareal", state: "active" },
    ],
  },
  {
    id: "SRV-10478",
    customerId: "c-4",
    customerName: "Rafael Ong",
    device: "Custom PC — Intel i5-12400F",
    issue: "Requesting SSD upgrade and OS migration.",
    status: "released",
    technician: "Ken Villareal",
    parts: [{ productId: "p-ssd-p3plus", name: "Crucial P3 Plus 2TB NVMe", qty: 1, price: 7200 }],
    labor: 1000,
    estimatedCost: 8200,
    actualCost: 8200,
    createdAt: daysAgo(9, 10),
    timeline: [
      { label: "Unit received", at: daysAgo(9, 10), actor: "Paolo Cruz", state: "done" },
      { label: "Upgrade complete", at: daysAgo(8, 13), actor: "Ken Villareal", state: "done" },
      { label: "Released", at: daysAgo(8, 16), actor: "Paolo Cruz", state: "done" },
    ],
  },
];

export const warranties: Warranty[] = [
  {
    id: "WR-20481",
    customerId: "c-1",
    customerName: "Juan Dela Cruz",
    productId: "p-gpu-5070",
    productName: "RTX 5070 Gaming OC 12GB",
    serial: "RTX5070-92831",
    orderId: "DPC-10482",
    purchasedAt: daysAgo(0, 9),
    expiresAt: daysAhead(1095),
    status: "active",
  },
  {
    id: "WR-20480",
    customerId: "c-1",
    customerName: "Juan Dela Cruz",
    productId: "p-cpu-7800x3d",
    productName: "AMD Ryzen 7 7800X3D",
    serial: "7800X3D-81204",
    orderId: "DPC-10482",
    purchasedAt: daysAgo(0, 9),
    expiresAt: daysAhead(1095),
    status: "active",
  },
  {
    id: "WR-20477",
    customerId: "c-3",
    customerName: "Maria Santiago",
    productId: "p-ssd-990pro",
    productName: "Samsung 990 PRO 1TB NVMe",
    serial: "990P-44120",
    orderId: "DPC-10479",
    purchasedAt: daysAgo(120, 11),
    expiresAt: daysAhead(1700),
    status: "active",
  },
  {
    id: "WR-20461",
    customerId: "c-5",
    customerName: "Bluewave Internet Cafe",
    productId: "p-psu-cv550",
    productName: "Corsair CV550 550W 80+ Bronze",
    orderId: "DPC-10475",
    purchasedAt: daysAgo(1080, 10),
    expiresAt: daysAhead(14),
    status: "expiring",
  },
  {
    id: "WR-20455",
    customerId: "c-6",
    customerName: "Ellaine Bautista",
    productId: "p-kb-k70",
    productName: "Corsair K70 RGB Mechanical",
    orderId: "DPC-10460",
    purchasedAt: daysAgo(800, 12),
    expiresAt: daysAgo(70),
    status: "expired",
  },
  {
    id: "WR-20452",
    customerId: "c-2",
    customerName: "Northline Creatives Inc.",
    productId: "p-mon-odyssey",
    productName: 'Samsung Odyssey G5 27" 165Hz',
    serial: "G5-27-77120",
    orderId: "DPC-10478",
    purchasedAt: daysAgo(200, 10),
    expiresAt: daysAhead(900),
    status: "active",
  },
];

export const warrantyClaims = [
  {
    id: "WC-3012",
    warrantyId: "WR-20461",
    reason: "PSU fails to power on intermittently.",
    status: "in_review" as const,
    createdAt: daysAgo(1, 13),
  },
  {
    id: "WC-3011",
    warrantyId: "WR-20452",
    reason: "Dead pixel cluster on lower-right quadrant.",
    status: "approved" as const,
    createdAt: daysAgo(6, 10),
    resolution: "Approved for supplier RMA replacement.",
  },
];

export const movements: InventoryMovement[] = [
  {
    id: "mv-1",
    productId: "p-gpu-5070",
    type: "reserved",
    qty: 1,
    at: daysAgo(0, 10),
    actor: "Dana Lim",
    reference: "DPC-10482",
  },
  {
    id: "mv-2",
    productId: "p-gpu-5070",
    type: "received",
    qty: 6,
    at: daysAgo(5, 9),
    actor: "Dana Lim",
    reference: "PO-8841",
  },
  {
    id: "mv-3",
    productId: "p-cpu-7800x3d",
    type: "sold",
    qty: 1,
    at: daysAgo(0, 9),
    actor: "Paolo Cruz",
    reference: "DPC-10482",
  },
  {
    id: "mv-4",
    productId: "p-ram-fury32",
    type: "sold",
    qty: 1,
    at: daysAgo(0, 14),
    actor: "Paolo Cruz",
    reference: "DPC-10480",
  },
  {
    id: "mv-5",
    productId: "p-cpu-14600kf",
    type: "damaged",
    qty: 1,
    at: daysAgo(3, 15),
    actor: "Dana Lim",
    note: "Bent pins on socket contact — supplier RMA filed.",
  },
  {
    id: "mv-6",
    productId: "p-hs-cloud3",
    type: "returned",
    qty: 1,
    at: daysAgo(4, 16),
    actor: "Paolo Cruz",
    reference: "DPC-10476",
  },
  {
    id: "mv-7",
    productId: "p-psu-cv550",
    type: "adjusted",
    qty: -1,
    at: daysAgo(7, 10),
    actor: "Mika Santos",
    note: "Cycle count correction.",
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "al-1",
    actor: "Justine Ramos",
    role: "owner",
    action: "created quote QT-10244",
    entity: "QT-10244",
    at: daysAgo(0, 8),
  },
  {
    id: "al-2",
    actor: "Ken Villareal",
    role: "technician",
    action: "started assembly on BUILD-10482",
    entity: "BUILD-10482",
    at: daysAgo(0, 11),
  },
  {
    id: "al-3",
    actor: "Paolo Cruz",
    role: "cashier",
    action: "completed order DPC-10481",
    entity: "DPC-10481",
    at: daysAgo(0, 13),
  },
  {
    id: "al-4",
    actor: "Dana Lim",
    role: "inventory",
    action: "received 6 units of GPU-RTX5070",
    entity: "p-gpu-5070",
    at: daysAgo(0, 9),
  },
  {
    id: "al-5",
    actor: "Mika Santos",
    role: "admin",
    action: "adjusted stock for PSU-CS-CV550",
    entity: "p-psu-cv550",
    at: daysAgo(1, 10),
  },
  {
    id: "al-6",
    actor: "Ken Villareal",
    role: "technician",
    action: "marked BUILD-10468 QA as passed",
    entity: "BUILD-10468",
    at: daysAgo(1, 15),
  },
];

export const notifications: AppNotification[] = [
  {
    id: "n-1",
    title: "Out of stock: HyperX Cloud III",
    body: "0 units available. 4 units below reorder point.",
    priority: "critical",
    at: daysAgo(0, 8),
    read: false,
    kind: "stock",
  },
  {
    id: "n-2",
    title: "Build ready for release",
    body: "BUILD-10468 passed QA and is awaiting customer pickup.",
    priority: "high",
    at: daysAgo(0, 9),
    read: false,
    kind: "build",
  },
  {
    id: "n-3",
    title: "Quote approved",
    body: "Northline Creatives Inc. approved QT-10243.",
    priority: "high",
    at: daysAgo(0, 10),
    read: false,
    kind: "quote",
  },
  {
    id: "n-4",
    title: "Warranty expiring in 14 days",
    body: "WR-20461 — Corsair CV550 for Bluewave Internet Cafe.",
    priority: "normal",
    at: daysAgo(1, 9),
    read: true,
    kind: "warranty",
  },
  {
    id: "n-5",
    title: "Service ticket updated",
    body: "SRV-10481 moved to Waiting for Parts.",
    priority: "normal",
    at: daysAgo(1, 11),
    read: true,
    kind: "service",
  },
];

/** Demo revenue series (30 days back → today). */
export const salesSeries = Array.from({ length: 30 }, (_, i) => {
  const d = new Date(now - (29 - i) * 86400000);
  const wave = Math.sin(i / 2.6) * 0.28 + Math.cos(i / 5) * 0.14;
  const weekend = [0, 6].includes(d.getDay()) ? 1.24 : 1;
  const revenue = Math.round((92000 + wave * 46000) * weekend);
  const orderCount = Math.max(6, Math.round(revenue / 5200));
  return {
    date: d.toISOString(),
    label: d.toLocaleDateString("en-PH", { month: "short", day: "numeric" }),
    revenue,
    orders: orderCount,
  };
});

export const hourlySeries = Array.from({ length: 11 }, (_, i) => {
  const hour = 9 + i;
  const rev = [4200, 8600, 12400, 9800, 7400, 15200, 18600, 12800, 16400, 14200, 8900][i];
  return { label: `${hour}:00`, date: "", revenue: rev, orders: Math.max(1, Math.round(rev / 5200)) };
});
