/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAssemblyRouteImport } from './routes/_app.assembly'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSerialsRouteImport } from './routes/_app.serials'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppAdminActivityRouteImport } from './routes/_app.admin.activity'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppAdminRolesRouteImport } from './routes/_app.admin.roles'
import { Route as AppAttributesIndexRouteImport } from './routes/_app.attributes.index'
import { Route as AppBrandsIndexRouteImport } from './routes/_app.brands.index'
import { Route as AppBuildsIndexRouteImport } from './routes/_app.builds.index'
import { Route as AppBuildsBuildIdRouteImport } from './routes/_app.builds.$buildId'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app.categories.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app.customers.$customerId'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppInventoryProductIdRouteImport } from './routes/_app.inventory.$productId'
import { Route as AppOrdersIndexRouteImport } from './routes/_app.orders.index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app.orders.$orderId'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppProductsProductIdRouteImport } from './routes/_app.products.$productId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppPurchasingIndexRouteImport } from './routes/_app.purchasing.index'
import { Route as AppPurchasingPoIdRouteImport } from './routes/_app.purchasing.$poId'
import { Route as AppQuotesIndexRouteImport } from './routes/_app.quotes.index'
import { Route as AppQuotesQuoteIdRouteImport } from './routes/_app.quotes.$quoteId'
import { Route as AppReceivingIndexRouteImport } from './routes/_app.receiving.index'
import { Route as AppReceivingReceiptIdRouteImport } from './routes/_app.receiving.$receiptId'
import { Route as AppReleasesIndexRouteImport } from './routes/_app.releases.index'
import { Route as AppReleasesReleaseIdRouteImport } from './routes/_app.releases.$releaseId'
import { Route as AppReturnsIndexRouteImport } from './routes/_app.returns.index'
import { Route as AppReturnsReturnIdRouteImport } from './routes/_app.returns.$returnId'
import { Route as AppServicesIndexRouteImport } from './routes/_app.services.index'
import { Route as AppServicesTicketIdRouteImport } from './routes/_app.services.$ticketId'
import { Route as AppShiftsIndexRouteImport } from './routes/_app.shifts.index'
import { Route as AppShiftsShiftIdRouteImport } from './routes/_app.shifts.$shiftId'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app.suppliers.index'
import { Route as AppSuppliersSupplierIdRouteImport } from './routes/_app.suppliers.$supplierId'
import { Route as AppTagsIndexRouteImport } from './routes/_app.tags.index'
import { Route as AppTransfersIndexRouteImport } from './routes/_app.transfers.index'
import { Route as AppWarehousesIndexRouteImport } from './routes/_app.warehouses.index'
import { Route as AppWarehousesWarehouseIdRouteImport } from './routes/_app.warehouses.$warehouseId'
import { Route as AppWarrantyIndexRouteImport } from './routes/_app.warranty.index'
import { Route as AppWarrantyWarrantyIdRouteImport } from './routes/_app.warranty.$warrantyId'
import { Route as AppAdministrationUsersIndexRouteImport } from './routes/_app.administration.users.index'
import { Route as AppAdministrationUsersAccountStatusRouteImport } from './routes/_app.administration.users.account-status'
import { Route as AppAdministrationUsersActivityRouteImport } from './routes/_app.administration.users.activity'
import { Route as AppAdministrationUsersBranchesRouteImport } from './routes/_app.administration.users.branches'
import { Route as AppAdministrationUsersLoginHistoryRouteImport } from './routes/_app.administration.users.login-history'
import { Route as AppAdministrationUsersNewRouteImport } from './routes/_app.administration.users.new'
import { Route as AppAdministrationUsersPasswordResetRouteImport } from './routes/_app.administration.users.password-reset'
import { Route as AppAdministrationUsersProfilesRouteImport } from './routes/_app.administration.users.profiles'
import { Route as AppAdministrationUsersRolesRouteImport } from './routes/_app.administration.users.roles'
import { Route as AppWarrantyClaimsClaimIdRouteImport } from './routes/_app.warranty.claims.$claimId'
import { Route as AppAdministrationUsersUserIdProfileRouteImport } from './routes/_app.administration.users.$userId.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssemblyRoute = AppAssemblyRouteImport.update({
  id: '/assembly',
  path: '/assembly',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSerialsRoute = AppSerialsRouteImport.update({
  id: '/serials',
  path: '/serials',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminActivityRoute = AppAdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAttributesIndexRoute = AppAttributesIndexRouteImport.update({
  id: '/attributes/',
  path: '/attributes/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsIndexRoute = AppBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildsIndexRoute = AppBuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildsBuildIdRoute = AppBuildsBuildIdRouteImport.update({
  id: '/builds/$buildId',
  path: '/builds/$buildId',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryProductIdRoute = AppInventoryProductIdRouteImport.update({
  id: '/inventory/$productId',
  path: '/inventory/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasingIndexRoute = AppPurchasingIndexRouteImport.update({
  id: '/purchasing/',
  path: '/purchasing/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasingPoIdRoute = AppPurchasingPoIdRouteImport.update({
  id: '/purchasing/$poId',
  path: '/purchasing/$poId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivingIndexRoute = AppReceivingIndexRouteImport.update({
  id: '/receiving/',
  path: '/receiving/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivingReceiptIdRoute = AppReceivingReceiptIdRouteImport.update({
  id: '/receiving/$receiptId',
  path: '/receiving/$receiptId',
  getParentRoute: () => AppRoute,
} as any)
const AppReleasesIndexRoute = AppReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => AppRoute,
} as any)
const AppReleasesReleaseIdRoute = AppReleasesReleaseIdRouteImport.update({
  id: '/releases/$releaseId',
  path: '/releases/$releaseId',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsIndexRoute = AppReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsReturnIdRoute = AppReturnsReturnIdRouteImport.update({
  id: '/returns/$returnId',
  path: '/returns/$returnId',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesTicketIdRoute = AppServicesTicketIdRouteImport.update({
  id: '/services/$ticketId',
  path: '/services/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsIndexRoute = AppShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsShiftIdRoute = AppShiftsShiftIdRouteImport.update({
  id: '/shifts/$shiftId',
  path: '/shifts/$shiftId',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersSupplierIdRoute = AppSuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsIndexRoute = AppTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersIndexRoute = AppTransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesIndexRoute = AppWarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesWarehouseIdRoute =
  AppWarehousesWarehouseIdRouteImport.update({
    id: '/warehouses/$warehouseId',
    path: '/warehouses/$warehouseId',
    getParentRoute: () => AppRoute,
  } as any)
const AppWarrantyIndexRoute = AppWarrantyIndexRouteImport.update({
  id: '/warranty/',
  path: '/warranty/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarrantyWarrantyIdRoute = AppWarrantyWarrantyIdRouteImport.update({
  id: '/warranty/$warrantyId',
  path: '/warranty/$warrantyId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministrationUsersIndexRoute =
  AppAdministrationUsersIndexRouteImport.update({
    id: '/administration/users/',
    path: '/administration/users/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersAccountStatusRoute =
  AppAdministrationUsersAccountStatusRouteImport.update({
    id: '/administration/users/account-status',
    path: '/administration/users/account-status',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersActivityRoute =
  AppAdministrationUsersActivityRouteImport.update({
    id: '/administration/users/activity',
    path: '/administration/users/activity',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersBranchesRoute =
  AppAdministrationUsersBranchesRouteImport.update({
    id: '/administration/users/branches',
    path: '/administration/users/branches',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersLoginHistoryRoute =
  AppAdministrationUsersLoginHistoryRouteImport.update({
    id: '/administration/users/login-history',
    path: '/administration/users/login-history',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersNewRoute =
  AppAdministrationUsersNewRouteImport.update({
    id: '/administration/users/new',
    path: '/administration/users/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersPasswordResetRoute =
  AppAdministrationUsersPasswordResetRouteImport.update({
    id: '/administration/users/password-reset',
    path: '/administration/users/password-reset',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersProfilesRoute =
  AppAdministrationUsersProfilesRouteImport.update({
    id: '/administration/users/profiles',
    path: '/administration/users/profiles',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersRolesRoute =
  AppAdministrationUsersRolesRouteImport.update({
    id: '/administration/users/roles',
    path: '/administration/users/roles',
    getParentRoute: () => AppRoute,
  } as any)
const AppWarrantyClaimsClaimIdRoute =
  AppWarrantyClaimsClaimIdRouteImport.update({
    id: '/warranty/claims/$claimId',
    path: '/warranty/claims/$claimId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdministrationUsersUserIdProfileRoute =
  AppAdministrationUsersUserIdProfileRouteImport.update({
    id: '/administration/users/$userId/profile',
    path: '/administration/users/$userId/profile',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assembly': typeof AppAssemblyRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/serials': typeof AppSerialsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/builds/$buildId': typeof AppBuildsBuildIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/inventory/$productId': typeof AppInventoryProductIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/purchasing/$poId': typeof AppPurchasingPoIdRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/receiving/$receiptId': typeof AppReceivingReceiptIdRoute
  '/releases/$releaseId': typeof AppReleasesReleaseIdRoute
  '/returns/$returnId': typeof AppReturnsReturnIdRoute
  '/services/$ticketId': typeof AppServicesTicketIdRoute
  '/shifts/$shiftId': typeof AppShiftsShiftIdRoute
  '/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
  '/warehouses/$warehouseId': typeof AppWarehousesWarehouseIdRoute
  '/warranty/$warrantyId': typeof AppWarrantyWarrantyIdRoute
  '/attributes/': typeof AppAttributesIndexRoute
  '/brands/': typeof AppBrandsIndexRoute
  '/builds/': typeof AppBuildsIndexRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/purchasing/': typeof AppPurchasingIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
  '/receiving/': typeof AppReceivingIndexRoute
  '/releases/': typeof AppReleasesIndexRoute
  '/returns/': typeof AppReturnsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/shifts/': typeof AppShiftsIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/tags/': typeof AppTagsIndexRoute
  '/transfers/': typeof AppTransfersIndexRoute
  '/warehouses/': typeof AppWarehousesIndexRoute
  '/warranty/': typeof AppWarrantyIndexRoute
  '/administration/users/account-status': typeof AppAdministrationUsersAccountStatusRoute
  '/administration/users/activity': typeof AppAdministrationUsersActivityRoute
  '/administration/users/branches': typeof AppAdministrationUsersBranchesRoute
  '/administration/users/login-history': typeof AppAdministrationUsersLoginHistoryRoute
  '/administration/users/new': typeof AppAdministrationUsersNewRoute
  '/administration/users/password-reset': typeof AppAdministrationUsersPasswordResetRoute
  '/administration/users/profiles': typeof AppAdministrationUsersProfilesRoute
  '/administration/users/roles': typeof AppAdministrationUsersRolesRoute
  '/warranty/claims/$claimId': typeof AppWarrantyClaimsClaimIdRoute
  '/administration/users/': typeof AppAdministrationUsersIndexRoute
  '/administration/users/$userId/profile': typeof AppAdministrationUsersUserIdProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assembly': typeof AppAssemblyRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/pos': typeof AppPosRoute
  '/reports': typeof AppReportsRoute
  '/serials': typeof AppSerialsRoute
  '/settings': typeof AppSettingsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/builds/$buildId': typeof AppBuildsBuildIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/inventory/$productId': typeof AppInventoryProductIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/purchasing/$poId': typeof AppPurchasingPoIdRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/receiving/$receiptId': typeof AppReceivingReceiptIdRoute
  '/releases/$releaseId': typeof AppReleasesReleaseIdRoute
  '/returns/$returnId': typeof AppReturnsReturnIdRoute
  '/services/$ticketId': typeof AppServicesTicketIdRoute
  '/shifts/$shiftId': typeof AppShiftsShiftIdRoute
  '/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
  '/warehouses/$warehouseId': typeof AppWarehousesWarehouseIdRoute
  '/warranty/$warrantyId': typeof AppWarrantyWarrantyIdRoute
  '/attributes': typeof AppAttributesIndexRoute
  '/brands': typeof AppBrandsIndexRoute
  '/builds': typeof AppBuildsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/purchasing': typeof AppPurchasingIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
  '/receiving': typeof AppReceivingIndexRoute
  '/releases': typeof AppReleasesIndexRoute
  '/returns': typeof AppReturnsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/shifts': typeof AppShiftsIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/tags': typeof AppTagsIndexRoute
  '/transfers': typeof AppTransfersIndexRoute
  '/warehouses': typeof AppWarehousesIndexRoute
  '/warranty': typeof AppWarrantyIndexRoute
  '/administration/users/account-status': typeof AppAdministrationUsersAccountStatusRoute
  '/administration/users/activity': typeof AppAdministrationUsersActivityRoute
  '/administration/users/branches': typeof AppAdministrationUsersBranchesRoute
  '/administration/users/login-history': typeof AppAdministrationUsersLoginHistoryRoute
  '/administration/users/new': typeof AppAdministrationUsersNewRoute
  '/administration/users/password-reset': typeof AppAdministrationUsersPasswordResetRoute
  '/administration/users/profiles': typeof AppAdministrationUsersProfilesRoute
  '/administration/users/roles': typeof AppAdministrationUsersRolesRoute
  '/warranty/claims/$claimId': typeof AppWarrantyClaimsClaimIdRoute
  '/administration/users': typeof AppAdministrationUsersIndexRoute
  '/administration/users/$userId/profile': typeof AppAdministrationUsersUserIdProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/assembly': typeof AppAssemblyRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/serials': typeof AppSerialsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/admin/activity': typeof AppAdminActivityRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/builds/$buildId': typeof AppBuildsBuildIdRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/inventory/$productId': typeof AppInventoryProductIdRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/purchasing/$poId': typeof AppPurchasingPoIdRoute
  '/_app/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/_app/receiving/$receiptId': typeof AppReceivingReceiptIdRoute
  '/_app/releases/$releaseId': typeof AppReleasesReleaseIdRoute
  '/_app/returns/$returnId': typeof AppReturnsReturnIdRoute
  '/_app/services/$ticketId': typeof AppServicesTicketIdRoute
  '/_app/shifts/$shiftId': typeof AppShiftsShiftIdRoute
  '/_app/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
  '/_app/warehouses/$warehouseId': typeof AppWarehousesWarehouseIdRoute
  '/_app/warranty/$warrantyId': typeof AppWarrantyWarrantyIdRoute
  '/_app/attributes/': typeof AppAttributesIndexRoute
  '/_app/brands/': typeof AppBrandsIndexRoute
  '/_app/builds/': typeof AppBuildsIndexRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/purchasing/': typeof AppPurchasingIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
  '/_app/receiving/': typeof AppReceivingIndexRoute
  '/_app/releases/': typeof AppReleasesIndexRoute
  '/_app/returns/': typeof AppReturnsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/shifts/': typeof AppShiftsIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/_app/tags/': typeof AppTagsIndexRoute
  '/_app/transfers/': typeof AppTransfersIndexRoute
  '/_app/warehouses/': typeof AppWarehousesIndexRoute
  '/_app/warranty/': typeof AppWarrantyIndexRoute
  '/_app/administration/users/account-status': typeof AppAdministrationUsersAccountStatusRoute
  '/_app/administration/users/activity': typeof AppAdministrationUsersActivityRoute
  '/_app/administration/users/branches': typeof AppAdministrationUsersBranchesRoute
  '/_app/administration/users/login-history': typeof AppAdministrationUsersLoginHistoryRoute
  '/_app/administration/users/new': typeof AppAdministrationUsersNewRoute
  '/_app/administration/users/password-reset': typeof AppAdministrationUsersPasswordResetRoute
  '/_app/administration/users/profiles': typeof AppAdministrationUsersProfilesRoute
  '/_app/administration/users/roles': typeof AppAdministrationUsersRolesRoute
  '/_app/warranty/claims/$claimId': typeof AppWarrantyClaimsClaimIdRoute
  '/_app/administration/users/': typeof AppAdministrationUsersIndexRoute
  '/_app/administration/users/$userId/profile': typeof AppAdministrationUsersUserIdProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assembly'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/pos'
    | '/reports'
    | '/serials'
    | '/settings'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/roles'
    | '/builds/$buildId'
    | '/customers/$customerId'
    | '/inventory/$productId'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/purchasing/$poId'
    | '/quotes/$quoteId'
    | '/receiving/$receiptId'
    | '/releases/$releaseId'
    | '/returns/$returnId'
    | '/services/$ticketId'
    | '/shifts/$shiftId'
    | '/suppliers/$supplierId'
    | '/warehouses/$warehouseId'
    | '/warranty/$warrantyId'
    | '/attributes/'
    | '/brands/'
    | '/builds/'
    | '/categories/'
    | '/customers/'
    | '/inventory/'
    | '/orders/'
    | '/products/'
    | '/projects/'
    | '/purchasing/'
    | '/quotes/'
    | '/receiving/'
    | '/releases/'
    | '/returns/'
    | '/services/'
    | '/shifts/'
    | '/suppliers/'
    | '/tags/'
    | '/transfers/'
    | '/warehouses/'
    | '/warranty/'
    | '/administration/users/account-status'
    | '/administration/users/activity'
    | '/administration/users/branches'
    | '/administration/users/login-history'
    | '/administration/users/new'
    | '/administration/users/password-reset'
    | '/administration/users/profiles'
    | '/administration/users/roles'
    | '/warranty/claims/$claimId'
    | '/administration/users/'
    | '/administration/users/$userId/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assembly'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/pos'
    | '/reports'
    | '/serials'
    | '/settings'
    | '/admin/activity'
    | '/admin/audit'
    | '/admin/roles'
    | '/builds/$buildId'
    | '/customers/$customerId'
    | '/inventory/$productId'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/purchasing/$poId'
    | '/quotes/$quoteId'
    | '/receiving/$receiptId'
    | '/releases/$releaseId'
    | '/returns/$returnId'
    | '/services/$ticketId'
    | '/shifts/$shiftId'
    | '/suppliers/$supplierId'
    | '/warehouses/$warehouseId'
    | '/warranty/$warrantyId'
    | '/attributes'
    | '/brands'
    | '/builds'
    | '/categories'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/projects'
    | '/purchasing'
    | '/quotes'
    | '/receiving'
    | '/releases'
    | '/returns'
    | '/services'
    | '/shifts'
    | '/suppliers'
    | '/tags'
    | '/transfers'
    | '/warehouses'
    | '/warranty'
    | '/administration/users/account-status'
    | '/administration/users/activity'
    | '/administration/users/branches'
    | '/administration/users/login-history'
    | '/administration/users/new'
    | '/administration/users/password-reset'
    | '/administration/users/profiles'
    | '/administration/users/roles'
    | '/warranty/claims/$claimId'
    | '/administration/users'
    | '/administration/users/$userId/profile'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/assembly'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/pos'
    | '/_app/reports'
    | '/_app/serials'
    | '/_app/settings'
    | '/_app/admin/activity'
    | '/_app/admin/audit'
    | '/_app/admin/roles'
    | '/_app/builds/$buildId'
    | '/_app/customers/$customerId'
    | '/_app/inventory/$productId'
    | '/_app/orders/$orderId'
    | '/_app/products/$productId'
    | '/_app/purchasing/$poId'
    | '/_app/quotes/$quoteId'
    | '/_app/receiving/$receiptId'
    | '/_app/releases/$releaseId'
    | '/_app/returns/$returnId'
    | '/_app/services/$ticketId'
    | '/_app/shifts/$shiftId'
    | '/_app/suppliers/$supplierId'
    | '/_app/warehouses/$warehouseId'
    | '/_app/warranty/$warrantyId'
    | '/_app/attributes/'
    | '/_app/brands/'
    | '/_app/builds/'
    | '/_app/categories/'
    | '/_app/customers/'
    | '/_app/inventory/'
    | '/_app/orders/'
    | '/_app/products/'
    | '/_app/projects/'
    | '/_app/purchasing/'
    | '/_app/quotes/'
    | '/_app/receiving/'
    | '/_app/releases/'
    | '/_app/returns/'
    | '/_app/services/'
    | '/_app/shifts/'
    | '/_app/suppliers/'
    | '/_app/tags/'
    | '/_app/transfers/'
    | '/_app/warehouses/'
    | '/_app/warranty/'
    | '/_app/administration/users/account-status'
    | '/_app/administration/users/activity'
    | '/_app/administration/users/branches'
    | '/_app/administration/users/login-history'
    | '/_app/administration/users/new'
    | '/_app/administration/users/password-reset'
    | '/_app/administration/users/profiles'
    | '/_app/administration/users/roles'
    | '/_app/warranty/claims/$claimId'
    | '/_app/administration/users/'
    | '/_app/administration/users/$userId/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/assembly': {
      id: '/_app/assembly'
      path: '/assembly'
      fullPath: '/assembly'
      preLoaderRoute: typeof AppAssemblyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/serials': {
      id: '/_app/serials'
      path: '/serials'
      fullPath: '/serials'
      preLoaderRoute: typeof AppSerialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/activity': {
      id: '/_app/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AppAdminActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attributes/': {
      id: '/_app/attributes/'
      path: '/attributes'
      fullPath: '/attributes/'
      preLoaderRoute: typeof AppAttributesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/': {
      id: '/_app/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AppBrandsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builds/': {
      id: '/_app/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof AppBuildsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builds/$buildId': {
      id: '/_app/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/builds/$buildId'
      preLoaderRoute: typeof AppBuildsBuildIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/$productId': {
      id: '/_app/inventory/$productId'
      path: '/inventory/$productId'
      fullPath: '/inventory/$productId'
      preLoaderRoute: typeof AppInventoryProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchasing/': {
      id: '/_app/purchasing/'
      path: '/purchasing'
      fullPath: '/purchasing/'
      preLoaderRoute: typeof AppPurchasingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchasing/$poId': {
      id: '/_app/purchasing/$poId'
      path: '/purchasing/$poId'
      fullPath: '/purchasing/$poId'
      preLoaderRoute: typeof AppPurchasingPoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/$quoteId': {
      id: '/_app/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receiving/': {
      id: '/_app/receiving/'
      path: '/receiving'
      fullPath: '/receiving/'
      preLoaderRoute: typeof AppReceivingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receiving/$receiptId': {
      id: '/_app/receiving/$receiptId'
      path: '/receiving/$receiptId'
      fullPath: '/receiving/$receiptId'
      preLoaderRoute: typeof AppReceivingReceiptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/releases/': {
      id: '/_app/releases/'
      path: '/releases'
      fullPath: '/releases/'
      preLoaderRoute: typeof AppReleasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/releases/$releaseId': {
      id: '/_app/releases/$releaseId'
      path: '/releases/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof AppReleasesReleaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns/': {
      id: '/_app/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof AppReturnsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns/$returnId': {
      id: '/_app/returns/$returnId'
      path: '/returns/$returnId'
      fullPath: '/returns/$returnId'
      preLoaderRoute: typeof AppReturnsReturnIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$ticketId': {
      id: '/_app/services/$ticketId'
      path: '/services/$ticketId'
      fullPath: '/services/$ticketId'
      preLoaderRoute: typeof AppServicesTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shifts/': {
      id: '/_app/shifts/'
      path: '/shifts'
      fullPath: '/shifts/'
      preLoaderRoute: typeof AppShiftsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shifts/$shiftId': {
      id: '/_app/shifts/$shiftId'
      path: '/shifts/$shiftId'
      fullPath: '/shifts/$shiftId'
      preLoaderRoute: typeof AppShiftsShiftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/$supplierId': {
      id: '/_app/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AppSuppliersSupplierIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags/': {
      id: '/_app/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AppTagsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers/': {
      id: '/_app/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof AppTransfersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouses/': {
      id: '/_app/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof AppWarehousesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouses/$warehouseId': {
      id: '/_app/warehouses/$warehouseId'
      path: '/warehouses/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof AppWarehousesWarehouseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warranty/': {
      id: '/_app/warranty/'
      path: '/warranty'
      fullPath: '/warranty/'
      preLoaderRoute: typeof AppWarrantyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warranty/$warrantyId': {
      id: '/_app/warranty/$warrantyId'
      path: '/warranty/$warrantyId'
      fullPath: '/warranty/$warrantyId'
      preLoaderRoute: typeof AppWarrantyWarrantyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/': {
      id: '/_app/administration/users/'
      path: '/administration/users'
      fullPath: '/administration/users/'
      preLoaderRoute: typeof AppAdministrationUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/account-status': {
      id: '/_app/administration/users/account-status'
      path: '/administration/users/account-status'
      fullPath: '/administration/users/account-status'
      preLoaderRoute: typeof AppAdministrationUsersAccountStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/activity': {
      id: '/_app/administration/users/activity'
      path: '/administration/users/activity'
      fullPath: '/administration/users/activity'
      preLoaderRoute: typeof AppAdministrationUsersActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/branches': {
      id: '/_app/administration/users/branches'
      path: '/administration/users/branches'
      fullPath: '/administration/users/branches'
      preLoaderRoute: typeof AppAdministrationUsersBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/login-history': {
      id: '/_app/administration/users/login-history'
      path: '/administration/users/login-history'
      fullPath: '/administration/users/login-history'
      preLoaderRoute: typeof AppAdministrationUsersLoginHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/new': {
      id: '/_app/administration/users/new'
      path: '/administration/users/new'
      fullPath: '/administration/users/new'
      preLoaderRoute: typeof AppAdministrationUsersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/password-reset': {
      id: '/_app/administration/users/password-reset'
      path: '/administration/users/password-reset'
      fullPath: '/administration/users/password-reset'
      preLoaderRoute: typeof AppAdministrationUsersPasswordResetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/profiles': {
      id: '/_app/administration/users/profiles'
      path: '/administration/users/profiles'
      fullPath: '/administration/users/profiles'
      preLoaderRoute: typeof AppAdministrationUsersProfilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/roles': {
      id: '/_app/administration/users/roles'
      path: '/administration/users/roles'
      fullPath: '/administration/users/roles'
      preLoaderRoute: typeof AppAdministrationUsersRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warranty/claims/$claimId': {
      id: '/_app/warranty/claims/$claimId'
      path: '/warranty/claims/$claimId'
      fullPath: '/warranty/claims/$claimId'
      preLoaderRoute: typeof AppWarrantyClaimsClaimIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administration/users/$userId/profile': {
      id: '/_app/administration/users/$userId/profile'
      path: '/administration/users/$userId/profile'
      fullPath: '/administration/users/$userId/profile'
      preLoaderRoute: typeof AppAdministrationUsersUserIdProfileRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssemblyRoute: typeof AppAssemblyRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppPosRoute: typeof AppPosRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSerialsRoute: typeof AppSerialsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminActivityRoute: typeof AppAdminActivityRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppBuildsBuildIdRoute: typeof AppBuildsBuildIdRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppInventoryProductIdRoute: typeof AppInventoryProductIdRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppPurchasingPoIdRoute: typeof AppPurchasingPoIdRoute
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRoute
  AppReceivingReceiptIdRoute: typeof AppReceivingReceiptIdRoute
  AppReleasesReleaseIdRoute: typeof AppReleasesReleaseIdRoute
  AppReturnsReturnIdRoute: typeof AppReturnsReturnIdRoute
  AppServicesTicketIdRoute: typeof AppServicesTicketIdRoute
  AppShiftsShiftIdRoute: typeof AppShiftsShiftIdRoute
  AppSuppliersSupplierIdRoute: typeof AppSuppliersSupplierIdRoute
  AppWarehousesWarehouseIdRoute: typeof AppWarehousesWarehouseIdRoute
  AppWarrantyWarrantyIdRoute: typeof AppWarrantyWarrantyIdRoute
  AppAttributesIndexRoute: typeof AppAttributesIndexRoute
  AppBrandsIndexRoute: typeof AppBrandsIndexRoute
  AppBuildsIndexRoute: typeof AppBuildsIndexRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppPurchasingIndexRoute: typeof AppPurchasingIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppReceivingIndexRoute: typeof AppReceivingIndexRoute
  AppReleasesIndexRoute: typeof AppReleasesIndexRoute
  AppReturnsIndexRoute: typeof AppReturnsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppShiftsIndexRoute: typeof AppShiftsIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppTagsIndexRoute: typeof AppTagsIndexRoute
  AppTransfersIndexRoute: typeof AppTransfersIndexRoute
  AppWarehousesIndexRoute: typeof AppWarehousesIndexRoute
  AppWarrantyIndexRoute: typeof AppWarrantyIndexRoute
  AppAdministrationUsersAccountStatusRoute: typeof AppAdministrationUsersAccountStatusRoute
  AppAdministrationUsersActivityRoute: typeof AppAdministrationUsersActivityRoute
  AppAdministrationUsersBranchesRoute: typeof AppAdministrationUsersBranchesRoute
  AppAdministrationUsersLoginHistoryRoute: typeof AppAdministrationUsersLoginHistoryRoute
  AppAdministrationUsersNewRoute: typeof AppAdministrationUsersNewRoute
  AppAdministrationUsersPasswordResetRoute: typeof AppAdministrationUsersPasswordResetRoute
  AppAdministrationUsersProfilesRoute: typeof AppAdministrationUsersProfilesRoute
  AppAdministrationUsersRolesRoute: typeof AppAdministrationUsersRolesRoute
  AppWarrantyClaimsClaimIdRoute: typeof AppWarrantyClaimsClaimIdRoute
  AppAdministrationUsersIndexRoute: typeof AppAdministrationUsersIndexRoute
  AppAdministrationUsersUserIdProfileRoute: typeof AppAdministrationUsersUserIdProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssemblyRoute: AppAssemblyRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppPosRoute: AppPosRoute,
  AppReportsRoute: AppReportsRoute,
  AppSerialsRoute: AppSerialsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminActivityRoute: AppAdminActivityRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppBuildsBuildIdRoute: AppBuildsBuildIdRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppInventoryProductIdRoute: AppInventoryProductIdRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppPurchasingPoIdRoute: AppPurchasingPoIdRoute,
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRoute,
  AppReceivingReceiptIdRoute: AppReceivingReceiptIdRoute,
  AppReleasesReleaseIdRoute: AppReleasesReleaseIdRoute,
  AppReturnsReturnIdRoute: AppReturnsReturnIdRoute,
  AppServicesTicketIdRoute: AppServicesTicketIdRoute,
  AppShiftsShiftIdRoute: AppShiftsShiftIdRoute,
  AppSuppliersSupplierIdRoute: AppSuppliersSupplierIdRoute,
  AppWarehousesWarehouseIdRoute: AppWarehousesWarehouseIdRoute,
  AppWarrantyWarrantyIdRoute: AppWarrantyWarrantyIdRoute,
  AppAttributesIndexRoute: AppAttributesIndexRoute,
  AppBrandsIndexRoute: AppBrandsIndexRoute,
  AppBuildsIndexRoute: AppBuildsIndexRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppPurchasingIndexRoute: AppPurchasingIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppReceivingIndexRoute: AppReceivingIndexRoute,
  AppReleasesIndexRoute: AppReleasesIndexRoute,
  AppReturnsIndexRoute: AppReturnsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppShiftsIndexRoute: AppShiftsIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppTagsIndexRoute: AppTagsIndexRoute,
  AppTransfersIndexRoute: AppTransfersIndexRoute,
  AppWarehousesIndexRoute: AppWarehousesIndexRoute,
  AppWarrantyIndexRoute: AppWarrantyIndexRoute,
  AppAdministrationUsersAccountStatusRoute:
    AppAdministrationUsersAccountStatusRoute,
  AppAdministrationUsersActivityRoute: AppAdministrationUsersActivityRoute,
  AppAdministrationUsersBranchesRoute: AppAdministrationUsersBranchesRoute,
  AppAdministrationUsersLoginHistoryRoute:
    AppAdministrationUsersLoginHistoryRoute,
  AppAdministrationUsersNewRoute: AppAdministrationUsersNewRoute,
  AppAdministrationUsersPasswordResetRoute:
    AppAdministrationUsersPasswordResetRoute,
  AppAdministrationUsersProfilesRoute: AppAdministrationUsersProfilesRoute,
  AppAdministrationUsersRolesRoute: AppAdministrationUsersRolesRoute,
  AppWarrantyClaimsClaimIdRoute: AppWarrantyClaimsClaimIdRoute,
  AppAdministrationUsersIndexRoute: AppAdministrationUsersIndexRoute,
  AppAdministrationUsersUserIdProfileRoute:
    AppAdministrationUsersUserIdProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
