/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAssemblyRouteImport } from './routes/_app.assembly'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppReleasesRouteImport } from './routes/_app.releases'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSerialsRouteImport } from './routes/_app.serials'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppBuildsIndexRouteImport } from './routes/_app.builds.index'
import { Route as AppBuildsBuildIdRouteImport } from './routes/_app.builds.$buildId'
import { Route as AppConsultationsIndexRouteImport } from './routes/_app.consultations.index'
import { Route as AppConsultationsConsultationIdRouteImport } from './routes/_app.consultations.$consultationId'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app.customers.$customerId'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppInventoryProductIdRouteImport } from './routes/_app.inventory.$productId'
import { Route as AppOrdersIndexRouteImport } from './routes/_app.orders.index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app.orders.$orderId'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppProductsProductIdRouteImport } from './routes/_app.products.$productId'
import { Route as AppPurchasingIndexRouteImport } from './routes/_app.purchasing.index'
import { Route as AppPurchasingPoIdRouteImport } from './routes/_app.purchasing.$poId'
import { Route as AppQuotesIndexRouteImport } from './routes/_app.quotes.index'
import { Route as AppQuotesQuoteIdRouteImport } from './routes/_app.quotes.$quoteId'
import { Route as AppReceivingIndexRouteImport } from './routes/_app.receiving.index'
import { Route as AppReceivingReceiptIdRouteImport } from './routes/_app.receiving.$receiptId'
import { Route as AppReleasesReleaseIdRouteImport } from './routes/_app.releases.$releaseId'
import { Route as AppReturnsIndexRouteImport } from './routes/_app.returns.index'
import { Route as AppReturnsReturnIdRouteImport } from './routes/_app.returns.$returnId'
import { Route as AppServicesIndexRouteImport } from './routes/_app.services.index'
import { Route as AppServicesTicketIdRouteImport } from './routes/_app.services.$ticketId'
import { Route as AppShiftsIndexRouteImport } from './routes/_app.shifts.index'
import { Route as AppShiftsShiftIdRouteImport } from './routes/_app.shifts.$shiftId'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app.suppliers.index'
import { Route as AppSuppliersSupplierIdRouteImport } from './routes/_app.suppliers.$supplierId'
import { Route as AppWarrantyIndexRouteImport } from './routes/_app.warranty.index'
import { Route as AppWarrantyWarrantyIdRouteImport } from './routes/_app.warranty.$warrantyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssemblyRoute = AppAssemblyRouteImport.update({
  id: '/assembly',
  path: '/assembly',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppReleasesRoute = AppReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSerialsRoute = AppSerialsRouteImport.update({
  id: '/serials',
  path: '/serials',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildsIndexRoute = AppBuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildsBuildIdRoute = AppBuildsBuildIdRouteImport.update({
  id: '/builds/$buildId',
  path: '/builds/$buildId',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationsIndexRoute = AppConsultationsIndexRouteImport.update({
  id: '/consultations/',
  path: '/consultations/',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationsConsultationIdRoute =
  AppConsultationsConsultationIdRouteImport.update({
    id: '/consultations/$consultationId',
    path: '/consultations/$consultationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryProductIdRoute = AppInventoryProductIdRouteImport.update({
  id: '/inventory/$productId',
  path: '/inventory/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasingIndexRoute = AppPurchasingIndexRouteImport.update({
  id: '/purchasing/',
  path: '/purchasing/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasingPoIdRoute = AppPurchasingPoIdRouteImport.update({
  id: '/purchasing/$poId',
  path: '/purchasing/$poId',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivingIndexRoute = AppReceivingIndexRouteImport.update({
  id: '/receiving/',
  path: '/receiving/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivingReceiptIdRoute = AppReceivingReceiptIdRouteImport.update({
  id: '/receiving/$receiptId',
  path: '/receiving/$receiptId',
  getParentRoute: () => AppRoute,
} as any)
const AppReleasesReleaseIdRoute = AppReleasesReleaseIdRouteImport.update({
  id: '/$releaseId',
  path: '/$releaseId',
  getParentRoute: () => AppReleasesRoute,
} as any)
const AppReturnsIndexRoute = AppReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsReturnIdRoute = AppReturnsReturnIdRouteImport.update({
  id: '/returns/$returnId',
  path: '/returns/$returnId',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesTicketIdRoute = AppServicesTicketIdRouteImport.update({
  id: '/services/$ticketId',
  path: '/services/$ticketId',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsIndexRoute = AppShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsShiftIdRoute = AppShiftsShiftIdRouteImport.update({
  id: '/shifts/$shiftId',
  path: '/shifts/$shiftId',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersSupplierIdRoute = AppSuppliersSupplierIdRouteImport.update({
  id: '/suppliers/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => AppRoute,
} as any)
const AppWarrantyIndexRoute = AppWarrantyIndexRouteImport.update({
  id: '/warranty/',
  path: '/warranty/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarrantyWarrantyIdRoute = AppWarrantyWarrantyIdRouteImport.update({
  id: '/warranty/$warrantyId',
  path: '/warranty/$warrantyId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assembly': typeof AppAssemblyRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/pos': typeof AppPosRoute
  '/releases': typeof AppReleasesRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/serials': typeof AppSerialsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/tasks': typeof AppTasksRoute
  '/builds/$buildId': typeof AppBuildsBuildIdRoute
  '/consultations/$consultationId': typeof AppConsultationsConsultationIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/inventory/$productId': typeof AppInventoryProductIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/purchasing/$poId': typeof AppPurchasingPoIdRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/receiving/$receiptId': typeof AppReceivingReceiptIdRoute
  '/releases/$releaseId': typeof AppReleasesReleaseIdRoute
  '/returns/$returnId': typeof AppReturnsReturnIdRoute
  '/services/$ticketId': typeof AppServicesTicketIdRoute
  '/shifts/$shiftId': typeof AppShiftsShiftIdRoute
  '/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
  '/warranty/$warrantyId': typeof AppWarrantyWarrantyIdRoute
  '/builds/': typeof AppBuildsIndexRoute
  '/consultations/': typeof AppConsultationsIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/purchasing/': typeof AppPurchasingIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
  '/receiving/': typeof AppReceivingIndexRoute
  '/returns/': typeof AppReturnsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/shifts/': typeof AppShiftsIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/warranty/': typeof AppWarrantyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assembly': typeof AppAssemblyRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/pos': typeof AppPosRoute
  '/releases': typeof AppReleasesRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/serials': typeof AppSerialsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/tasks': typeof AppTasksRoute
  '/builds/$buildId': typeof AppBuildsBuildIdRoute
  '/consultations/$consultationId': typeof AppConsultationsConsultationIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/inventory/$productId': typeof AppInventoryProductIdRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/purchasing/$poId': typeof AppPurchasingPoIdRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/receiving/$receiptId': typeof AppReceivingReceiptIdRoute
  '/releases/$releaseId': typeof AppReleasesReleaseIdRoute
  '/returns/$returnId': typeof AppReturnsReturnIdRoute
  '/services/$ticketId': typeof AppServicesTicketIdRoute
  '/shifts/$shiftId': typeof AppShiftsShiftIdRoute
  '/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
  '/warranty/$warrantyId': typeof AppWarrantyWarrantyIdRoute
  '/builds': typeof AppBuildsIndexRoute
  '/consultations': typeof AppConsultationsIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/purchasing': typeof AppPurchasingIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
  '/receiving': typeof AppReceivingIndexRoute
  '/returns': typeof AppReturnsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/shifts': typeof AppShiftsIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/warranty': typeof AppWarrantyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/assembly': typeof AppAssemblyRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/releases': typeof AppReleasesRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/serials': typeof AppSerialsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/builds/$buildId': typeof AppBuildsBuildIdRoute
  '/_app/consultations/$consultationId': typeof AppConsultationsConsultationIdRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/inventory/$productId': typeof AppInventoryProductIdRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/purchasing/$poId': typeof AppPurchasingPoIdRoute
  '/_app/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/_app/receiving/$receiptId': typeof AppReceivingReceiptIdRoute
  '/_app/releases/$releaseId': typeof AppReleasesReleaseIdRoute
  '/_app/returns/$returnId': typeof AppReturnsReturnIdRoute
  '/_app/services/$ticketId': typeof AppServicesTicketIdRoute
  '/_app/shifts/$shiftId': typeof AppShiftsShiftIdRoute
  '/_app/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
  '/_app/warranty/$warrantyId': typeof AppWarrantyWarrantyIdRoute
  '/_app/builds/': typeof AppBuildsIndexRoute
  '/_app/consultations/': typeof AppConsultationsIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/purchasing/': typeof AppPurchasingIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
  '/_app/receiving/': typeof AppReceivingIndexRoute
  '/_app/returns/': typeof AppReturnsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/shifts/': typeof AppShiftsIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/_app/warranty/': typeof AppWarrantyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assembly'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/pos'
    | '/releases'
    | '/reports'
    | '/serials'
    | '/settings'
    | '/staff'
    | '/tasks'
    | '/builds/$buildId'
    | '/consultations/$consultationId'
    | '/customers/$customerId'
    | '/inventory/$productId'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/purchasing/$poId'
    | '/quotes/$quoteId'
    | '/receiving/$receiptId'
    | '/releases/$releaseId'
    | '/returns/$returnId'
    | '/services/$ticketId'
    | '/shifts/$shiftId'
    | '/suppliers/$supplierId'
    | '/warranty/$warrantyId'
    | '/builds/'
    | '/consultations/'
    | '/customers/'
    | '/inventory/'
    | '/orders/'
    | '/products/'
    | '/purchasing/'
    | '/quotes/'
    | '/receiving/'
    | '/returns/'
    | '/services/'
    | '/shifts/'
    | '/suppliers/'
    | '/warranty/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assembly'
    | '/audit'
    | '/dashboard'
    | '/documents'
    | '/pos'
    | '/releases'
    | '/reports'
    | '/serials'
    | '/settings'
    | '/staff'
    | '/tasks'
    | '/builds/$buildId'
    | '/consultations/$consultationId'
    | '/customers/$customerId'
    | '/inventory/$productId'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/purchasing/$poId'
    | '/quotes/$quoteId'
    | '/receiving/$receiptId'
    | '/releases/$releaseId'
    | '/returns/$returnId'
    | '/services/$ticketId'
    | '/shifts/$shiftId'
    | '/suppliers/$supplierId'
    | '/warranty/$warrantyId'
    | '/builds'
    | '/consultations'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/purchasing'
    | '/quotes'
    | '/receiving'
    | '/returns'
    | '/services'
    | '/shifts'
    | '/suppliers'
    | '/warranty'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/assembly'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/pos'
    | '/_app/releases'
    | '/_app/reports'
    | '/_app/serials'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/tasks'
    | '/_app/builds/$buildId'
    | '/_app/consultations/$consultationId'
    | '/_app/customers/$customerId'
    | '/_app/inventory/$productId'
    | '/_app/orders/$orderId'
    | '/_app/products/$productId'
    | '/_app/purchasing/$poId'
    | '/_app/quotes/$quoteId'
    | '/_app/receiving/$receiptId'
    | '/_app/releases/$releaseId'
    | '/_app/returns/$returnId'
    | '/_app/services/$ticketId'
    | '/_app/shifts/$shiftId'
    | '/_app/suppliers/$supplierId'
    | '/_app/warranty/$warrantyId'
    | '/_app/builds/'
    | '/_app/consultations/'
    | '/_app/customers/'
    | '/_app/inventory/'
    | '/_app/orders/'
    | '/_app/products/'
    | '/_app/purchasing/'
    | '/_app/quotes/'
    | '/_app/receiving/'
    | '/_app/returns/'
    | '/_app/services/'
    | '/_app/shifts/'
    | '/_app/suppliers/'
    | '/_app/warranty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/assembly': {
      id: '/_app/assembly'
      path: '/assembly'
      fullPath: '/assembly'
      preLoaderRoute: typeof AppAssemblyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/releases': {
      id: '/_app/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof AppReleasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/serials': {
      id: '/_app/serials'
      path: '/serials'
      fullPath: '/serials'
      preLoaderRoute: typeof AppSerialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builds/': {
      id: '/_app/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof AppBuildsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builds/$buildId': {
      id: '/_app/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/builds/$buildId'
      preLoaderRoute: typeof AppBuildsBuildIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultations/': {
      id: '/_app/consultations/'
      path: '/consultations'
      fullPath: '/consultations/'
      preLoaderRoute: typeof AppConsultationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultations/$consultationId': {
      id: '/_app/consultations/$consultationId'
      path: '/consultations/$consultationId'
      fullPath: '/consultations/$consultationId'
      preLoaderRoute: typeof AppConsultationsConsultationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/$productId': {
      id: '/_app/inventory/$productId'
      path: '/inventory/$productId'
      fullPath: '/inventory/$productId'
      preLoaderRoute: typeof AppInventoryProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchasing/': {
      id: '/_app/purchasing/'
      path: '/purchasing'
      fullPath: '/purchasing/'
      preLoaderRoute: typeof AppPurchasingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchasing/$poId': {
      id: '/_app/purchasing/$poId'
      path: '/purchasing/$poId'
      fullPath: '/purchasing/$poId'
      preLoaderRoute: typeof AppPurchasingPoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/$quoteId': {
      id: '/_app/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receiving/': {
      id: '/_app/receiving/'
      path: '/receiving'
      fullPath: '/receiving/'
      preLoaderRoute: typeof AppReceivingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receiving/$receiptId': {
      id: '/_app/receiving/$receiptId'
      path: '/receiving/$receiptId'
      fullPath: '/receiving/$receiptId'
      preLoaderRoute: typeof AppReceivingReceiptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/releases/$releaseId': {
      id: '/_app/releases/$releaseId'
      path: '/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof AppReleasesReleaseIdRouteImport
      parentRoute: typeof AppReleasesRoute
    }
    '/_app/returns/': {
      id: '/_app/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof AppReturnsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns/$returnId': {
      id: '/_app/returns/$returnId'
      path: '/returns/$returnId'
      fullPath: '/returns/$returnId'
      preLoaderRoute: typeof AppReturnsReturnIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$ticketId': {
      id: '/_app/services/$ticketId'
      path: '/services/$ticketId'
      fullPath: '/services/$ticketId'
      preLoaderRoute: typeof AppServicesTicketIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shifts/': {
      id: '/_app/shifts/'
      path: '/shifts'
      fullPath: '/shifts/'
      preLoaderRoute: typeof AppShiftsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shifts/$shiftId': {
      id: '/_app/shifts/$shiftId'
      path: '/shifts/$shiftId'
      fullPath: '/shifts/$shiftId'
      preLoaderRoute: typeof AppShiftsShiftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/$supplierId': {
      id: '/_app/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AppSuppliersSupplierIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warranty/': {
      id: '/_app/warranty/'
      path: '/warranty'
      fullPath: '/warranty/'
      preLoaderRoute: typeof AppWarrantyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warranty/$warrantyId': {
      id: '/_app/warranty/$warrantyId'
      path: '/warranty/$warrantyId'
      fullPath: '/warranty/$warrantyId'
      preLoaderRoute: typeof AppWarrantyWarrantyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppReleasesRouteChildren {
  AppReleasesReleaseIdRoute: typeof AppReleasesReleaseIdRoute
}

const AppReleasesRouteChildren: AppReleasesRouteChildren = {
  AppReleasesReleaseIdRoute: AppReleasesReleaseIdRoute,
}

const AppReleasesRouteWithChildren = AppReleasesRoute._addFileChildren(
  AppReleasesRouteChildren,
)

interface AppRouteChildren {
  AppAssemblyRoute: typeof AppAssemblyRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppPosRoute: typeof AppPosRoute
  AppReleasesRoute: typeof AppReleasesRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSerialsRoute: typeof AppSerialsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTasksRoute: typeof AppTasksRoute
  AppBuildsBuildIdRoute: typeof AppBuildsBuildIdRoute
  AppConsultationsConsultationIdRoute: typeof AppConsultationsConsultationIdRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppInventoryProductIdRoute: typeof AppInventoryProductIdRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppPurchasingPoIdRoute: typeof AppPurchasingPoIdRoute
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRoute
  AppReceivingReceiptIdRoute: typeof AppReceivingReceiptIdRoute
  AppReturnsReturnIdRoute: typeof AppReturnsReturnIdRoute
  AppServicesTicketIdRoute: typeof AppServicesTicketIdRoute
  AppShiftsShiftIdRoute: typeof AppShiftsShiftIdRoute
  AppSuppliersSupplierIdRoute: typeof AppSuppliersSupplierIdRoute
  AppWarrantyWarrantyIdRoute: typeof AppWarrantyWarrantyIdRoute
  AppBuildsIndexRoute: typeof AppBuildsIndexRoute
  AppConsultationsIndexRoute: typeof AppConsultationsIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppPurchasingIndexRoute: typeof AppPurchasingIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppReceivingIndexRoute: typeof AppReceivingIndexRoute
  AppReturnsIndexRoute: typeof AppReturnsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppShiftsIndexRoute: typeof AppShiftsIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppWarrantyIndexRoute: typeof AppWarrantyIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssemblyRoute: AppAssemblyRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppPosRoute: AppPosRoute,
  AppReleasesRoute: AppReleasesRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSerialsRoute: AppSerialsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppTasksRoute: AppTasksRoute,
  AppBuildsBuildIdRoute: AppBuildsBuildIdRoute,
  AppConsultationsConsultationIdRoute: AppConsultationsConsultationIdRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppInventoryProductIdRoute: AppInventoryProductIdRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppPurchasingPoIdRoute: AppPurchasingPoIdRoute,
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRoute,
  AppReceivingReceiptIdRoute: AppReceivingReceiptIdRoute,
  AppReturnsReturnIdRoute: AppReturnsReturnIdRoute,
  AppServicesTicketIdRoute: AppServicesTicketIdRoute,
  AppShiftsShiftIdRoute: AppShiftsShiftIdRoute,
  AppSuppliersSupplierIdRoute: AppSuppliersSupplierIdRoute,
  AppWarrantyWarrantyIdRoute: AppWarrantyWarrantyIdRoute,
  AppBuildsIndexRoute: AppBuildsIndexRoute,
  AppConsultationsIndexRoute: AppConsultationsIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppPurchasingIndexRoute: AppPurchasingIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppReceivingIndexRoute: AppReceivingIndexRoute,
  AppReturnsIndexRoute: AppReturnsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppShiftsIndexRoute: AppShiftsIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppWarrantyIndexRoute: AppWarrantyIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
